### ISSUE TITLE
inSARFlow for different time-series packages

### ISSUE THREAD

**Issue by stoormgeo** [levuvietphong/InSARFlow#1]
Hi, thanks for your application!
I'am using ISCE and want to speedup data processing with inSARFlow.
Is there a way to use inSARFlow for further processing in other time series analysis packages (e.g. StaMPS)? We only need coregistered SLC, baseline grids and reference geometry data. 
Can I use CUDA functionality in ISCE calculations using inSARFlow?

**Comment by levuvietphong** [comment]
No, InSARFlow doesn't support CUDA now
